---
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment to deploy to'
        required: true
        default: dev

env:
  CLOUD_RUN_PROJECT_ID: ${{ vars.CLOUD_RUN_PROJECT_ID }}
  CLOUD_RUN_SERVICE_ACCOUNT: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
  CLOUD_RUN_SERVICE_ACCOUNT_EMAIL: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}
  SERVERLESS_VPC_CONNECTOR: ${{ secrets.SERVERLESS_VPC_CONNECTOR }}
  DB_URL: ${{ secrets.DB_URL }}
  CLOUD_RUN_REGION: ${{ vars.CLOUD_RUN_REGION }}
  CLOUDSQL_INSTANCE_ID: ${{ secrets.CLOUDSQL_INSTANCE_ID }}
  REPO_NAME: ${{ vars.REPO_NAME }}

jobs:
  build-and-deploy:
    name: setup, build, and deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # this step is where our service account will be authenticated
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.CLOUD_RUN_PROJECT_ID }}
          service_account_key: ${{ env.CLOUD_RUN_SERVICE_ACCOUNT }}
          service_account_email: ${{ env.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}

      - name: enable the necessary apis and enable docker auth
        run: |-
          gcloud services enable containerregistry.googleapis.com
          gcloud services enable run.googleapis.com
          gcloud --quiet auth configure-docker

      - name: build and tag image
        run: |-
          docker build . --build-arg DATABASE_URL=$DB_URL --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"

      - name: push image to gcr
        run: |-
          docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA

      - name: run db migrations
        run: |-
          gcloud components install beta --quiet
          gcloud beta run jobs create "db-migrations-${GITHUB_SHA::7}" --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
            --set-env-vars DATABASE_URL=$DB_URL \
            --set-cloudsql-instances $CLOUD_RUN_PROJECT_ID:$CLOUD_RUN_REGION:$CLOUDSQL_INSTANCE_ID \
            --vpc-connector $SERVERLESS_VPC_CONNECTOR \
            --region $CLOUD_RUN_REGION \
            --command "/bin/sh" --args="/app/scripts/migrate.sh" \
            --wait

      - name: deploy
        run: |-
          gcloud components install beta --quiet
          gcloud beta run deploy $REPO_NAME --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
            --project $CLOUD_RUN_PROJECT_ID \
            --platform managed \
            --region $CLOUD_RUN_REGION \
            --vpc-connector $SERVERLESS_VPC_CONNECTOR \
            --set-env-vars DATABASE_URL=$DB_URL \
            --add-cloudsql-instances $CLOUD_RUN_PROJECT_ID:$CLOUD_RUN_REGION:$CLOUDSQL_INSTANCE_ID \
            --allow-unauthenticated \
            --quiet